
micronaut:
  server:
    port: 8083

data:
  mongodb:
    database: admin
    uri: ${MONGO_DB_URI:mongodb://admin:123456@localhost:27017}


jpa:
  default:
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: update
    entity-scan:
      packages: com.tables.models

redis:
  uri: redis://localhost:6379
  ssl: true
  timeout: 30s
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  caches:
    products:
      expire-after-write: 60s

flyway:
  datasources:
    default:
      enabled: true


kafka:
  bootstrap:
    servers: localhost:9092

