micronaut:
  server:
    port: 3000


kafka:
  bootstrap:
    servers: localhost:9092
  consumer:
    group-id: orquestrator-group
    auto-offset-reset: latest

logger:
  levels:
    org.apache.kafka: OFF
